apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: am-payments
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: am-payments
  targetCPUUtilizationPercentage: 70
